apiVersion: carto.run/v1alpha1
kind: Deliverable
metadata:
  name: ss-friday-java-web-app
  namespace: jeremy
  labels:
    app.kubernetes.io/part-of: ss-friday-java-web-app
    apps.tanzu.vmware.com/auto-configure-actuators: "true"
    apps.tanzu.vmware.com/workload-type: statefulset
    app.kubernetes.io/component: deliverable
    app.tanzu.vmware.com/deliverable-type: web
    carto.run/cluster-template-name: config-deliverable-template
    carto.run/resource-name: create-deliverable
    carto.run/supply-chain-name: source-to-url
    carto.run/template-kind: ClusterConfigTemplate
    carto.run/template-lifecycle: mutable
    carto.run/workload-name: ss-friday-java-web-app
    carto.run/workload-namespace: jeremy
spec:
  params:
  - name: gitops_ssh_secret
    value: tenant-gitops-ssh
  source:
    git:
      url: ssh://git@github.com/Mpluya/tap-azure-workload-config-repo.git
      ref:
        branch: main
    subPath: config/jeremy/ss-friday-java-web-app/dev

