#@ load("@ytt:data", "data")
---
apiVersion: carto.run/v1alpha1
kind: Deliverable
metadata:
  name: go-app
  namespace: demo
  labels:
    app.kubernetes.io/part-of: go-app
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    tanzu.app.live.view: "true"
    app.kubernetes.io/component: deliverable
    app.tanzu.vmware.com/deliverable-type: web
spec:
  params:
  - name: gitops_ssh_secret
    value: tenant-gitops-ssh
  source:
    subPath: config/demo/go-app
    git:
      url: ssh://git@github.com/Mpluya/tap-azure-workload-config-repo.git

      ref:
        branch: #@ data.values.gitops.branch
