apiVersion: carto.run/v1alpha1
kind: Deliverable
metadata:
  name: friday-java-web-app
  namespace: jeremy
  labels:
    app.kubernetes.io/part-of: friday-java-web-app
    apps.tanzu.vmware.com/auto-configure-actuators: "true"
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/component: deliverable
    app.tanzu.vmware.com/deliverable-type: web
spec:
  params:
  - name: gitops_ssh_secret
    value: tenant-gitops-ssh
  source:
    git:
      url: ssh://git@github.com/Mpluya/tap-azure-workload-config-repo.git
      ref:
        branch: main
    subPath: config/jeremy/friday-java-web-app/dev

