apiVersion: carto.run/v1alpha1
kind: Deliverable
metadata:
  name: hello
  namespace: mae
  labels:
    aggregate-name: hello-system
    app.kubernetes.io/part-of: hello
    apps.tanzu.vmware.com/auto-configure-actuators: "true"
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    backstage.io/kubernetes-id: hello-system
    app.kubernetes.io/component: deliverable
    app.tanzu.vmware.com/deliverable-type: web
    carto.run/cluster-template-name: config-deliverable-template
    carto.run/resource-name: create-deliverable
    carto.run/supply-chain-name: source-test-scan-to-url
    carto.run/template-kind: ClusterConfigTemplate
    carto.run/template-lifecycle: mutable
    carto.run/workload-name: hello
    carto.run/workload-namespace: mae
spec:
  params:
  - name: gitops_ssh_secret
    value: tenant-gitops-ssh
  source:
    git:
      url: ssh://git@github.com/Mpluya/tap-azure-workload-config-repo.git
      ref:
        branch: main
    subPath: config/mae/hello/dev

