apiVersion: carto.run/v1alpha1
kind: Deliverable
metadata:
  name: appsso-starter-java
  namespace: jeremy
  labels:
    app.kubernetes.io/part-of: appsso-starter-java
    apps.tanzu.vmware.com/workload-type: web
    autoscaling.knative.dev/min-scale: "1"
    app.kubernetes.io/component: deliverable
    app.tanzu.vmware.com/deliverable-type: web
    carto.run/cluster-template-name: config-deliverable-template
    carto.run/resource-name: create-deliverable
    carto.run/supply-chain-name: source-to-url
    carto.run/template-kind: ClusterConfigTemplate
    carto.run/template-lifecycle: mutable
    carto.run/workload-name: appsso-starter-java
    carto.run/workload-namespace: jeremy
spec:
  params:
  - name: gitops_ssh_secret
    value: tenant-gitops-ssh
  source:
    git:
      url: ssh://git@github.com/Mpluya/tap-azure-workload-config-repo.git
      ref:
        branch: main
    subPath: config/jeremy/appsso-starter-java/dev

