apiVersion: carto.run/v1alpha1
kind: Deliverable
metadata:
  name: workload-with-git-sha
  namespace: mae
  labels:
    app.kubernetes.io/part-of: workload-with-git-sha
    apps.tanzu.vmware.com/auto-configure-actuators: "true"
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: server-with-git-annotation
    app.kubernetes.io/component: deliverable
    app.tanzu.vmware.com/deliverable-type: web
spec:
  params:
  - name: gitops_ssh_secret
    value: tenant-gitops-ssh
  source:
    git:
      url: ssh://git@github.com/Mpluya/tap-azure-workload-config-repo.git
      ref:
        branch: main
    subPath: config/mae/workload-with-git-sha/dev

