#@ load("@ytt:data", "data")
---
apiVersion: carto.run/v1alpha1
kind: Deliverable
metadata:
  name: tanzu-java-web-app-1-6
  namespace: mae
  labels:
    app.kubernetes.io/part-of: tanzu-java-web-app-1-6
    apps.tanzu.vmware.com/auto-configure-actuators: "true"
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/component: deliverable
    app.tanzu.vmware.com/deliverable-type: web
spec:
  params:
  - name: gitops_ssh_secret
    value: tenant-gitops-ssh
  source:
    subPath: config/mae/tanzu-java-web-app-1-6
    git:
      url: ssh://git@github.com/Mpluya/tap-azure-workload-config-repo.git

      ref:
        branch: #@ data.values.gitops.branch
